const Result = require("../models/Result");
const Student = require("../models/Student");
const getResults = async (req,res)=>{try{const {studentId,courseCode}=req.query;const filter={};if(studentId)filter.studentId=String(studentId).trim();if(courseCode)filter.courseCode=String(courseCode).trim();return res.json(await Result.find(filter).sort({createdAt:-1}));}catch(error){return res.status(500).json({message:"Failed to fetch results.",error:error.message});}};
const getStudentResults = async (req,res)=>{try{const studentId=String(req.params.studentId).trim();return res.json(await Result.find({$or:[{studentId},{studentId:{$regex:new RegExp(`^${studentId}$`,"i")}}]}).sort({createdAt:-1}));}catch(error){return res.status(500).json({message:"Failed to fetch student results.",error:error.message});}};
const getResultById = async (req,res)=>{try{const {id}=req.params;let result=null;if(/^[0-9a-fA-F]{24}$/.test(id))result=await Result.findById(id);if(!result){const results=await Result.find({studentId:id});if(results.length)return res.json(results);return res.status(404).json({message:"Result not found."});}return res.json(result);}catch(error){return res.status(500).json({message:"Failed to retrieve result.",error:error.message});}};
const saveResult = async (req,res)=>{try{const {studentId,courseCode,courseName,assignmentScore,examScore,score}=req.body||{};if(!studentId||!courseCode||!courseName)return res.status(400).json({message:"Student ID, course code, and course name are required."});const trimmedId=String(studentId).trim();const aScore=assignmentScore!==undefined?Number(assignmentScore):0;const eScore=examScore!==undefined?Number(examScore):(score!==undefined?Number(score):0);const {finalScore,grade,status}=Result.calculateResult(aScore,eScore);const student=await Student.findOne({studentId:{$regex:new RegExp(`^${trimmedId}$`,"i")}});let result=await Result.findOne({studentId:trimmedId,courseCode:String(courseCode).trim()});if(result){Object.assign(result,{assignmentScore:aScore,examScore:eScore,finalScore,grade,status,courseName:String(courseName).trim()});if(student)result.studentRef=student._id;await result.save();}else result=await Result.create({studentId:trimmedId,studentRef:student?._id,courseCode:String(courseCode).trim(),courseName:String(courseName).trim(),assignmentScore:aScore,examScore:eScore,finalScore,grade,status});if(student){const allResults=await Result.find({studentId:student.studentId});if(allResults.length){student.gpa=parseFloat(((allResults.reduce((a,r)=>a+r.finalScore,0)/allResults.length)/25).toFixed(2));await student.save();}}return res.status(201).json({message:"Result recorded successfully.",result});}catch(error){return res.status(500).json({message:"Failed to record result.",error:error.message});}};
const updateResult = async (req,res)=>{try{const result=await Result.findById(req.params.id);if(!result)return res.status(404).json({message:"Result not found."});const {assignmentScore,examScore,courseName}=req.body||{};const aScore=assignmentScore!==undefined?Number(assignmentScore):result.assignmentScore;const eScore=examScore!==undefined?Number(examScore):result.examScore;const {finalScore,grade,status}=Result.calculateResult(aScore,eScore);Object.assign(result,{assignmentScore:aScore,examScore:eScore,finalScore,grade,status});if(courseName)result.courseName=courseName;await result.save();return res.json({message:"Result updated successfully.",result});}catch(error){return res.status(500).json({message:"Failed to update result.",error:error.message});}};
const deleteResult = async (req,res)=>{try{const result=await Result.findByIdAndDelete(req.params.id);if(!result)return res.status(404).json({message:"Result not found."});return res.json({message:"Result removed successfully."});}catch(error){return res.status(500).json({message:"Failed to delete result.",error:error.message});}};
module.exports={getResults,getStudentResults,getResultById,saveResult,updateResult,deleteResult};
